build:
  version: "3.0"

loans:
  message: "Welcome to DemoBank loans related local APIs"
  contactDetails:
    name: "Carlos Perez - Developer"
    email: "carlosjulioperez@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 777-1234