build:
  version: "2.0"

loans:
  message: "Welcome to DemoBank loans related QA APIs"
  contactDetails:
    name: "Ana Scott - QA Lead"
    email: "anascott@gmail.com"
  onCallSupport:
    - (444) 555-1234
    - (444) 777-1234
